# Write a function so that the columns of the output matrix are powers of the input vector. 


## The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 


In [1]:
def vander(arr, N, increasing):
    import numpy as np
    length = len(arr)
    arr = np.array(arr).reshape(length, 1)
    result = np.zeros((length, N), dtype='int64')
    result = result + arr
    power = []
    for i in range(N):
        power.append(N-i-1)
    if increasing:
        power = list(reversed(power))
    power = np.array(power)
    result = result ** power
    return result

In [2]:
solution = vander(arr=[7, 5, 3, 1], N=3, increasing=False)
print(solution)

[[49  7  1]
 [25  5  1]
 [ 9  3  1]
 [ 1  1  1]]


# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 

#### The moving average sequence has n-k+1 elements as shown below. 
#### The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
#### i 1 2 3 4 5 6 7 8 9 10 
#### ===== == == == == == == == == == == 
#### Input 10 20 30 40 50 60 70 80 90 100  
#### y1 25 = (10+20+30+40)/4 
#### y2 35 = (20+30+40+50)/4 
#### y3 45 = (30+40+50+60)/4 
#### y4 55 = (40+50+60+70)/4 
#### y5 65 = (50+60+70+80)/4 
#### y6 75 = (60+70+80+90)/4 
#### y7 85 = (70+80+90+100)/4

#### Thus, the moving average sequence has n-k+1=10-4+1=7 values.
#### Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [5]:
def Movingaverage(array, k):
    arr = []
    moving_average = []

    for i in range(0, len(array)):

        if i <= k-1:
            arr.append(array[i])  
        else:
            print(arr)

            moving_average.append(np.array(arr).mean())
            del arr[0]
            arr.append(array[i])

    moving_average.append(sum(arr)/k)


    print(arr)
    print()
    print("Moving average array is: ", moving_average)
    print("Lenght of moving average array is: ",len(moving_average))

From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

## 4. Delete the From_To column from df and attach the temporary DataFrame from the previous questions. 

In [6]:
array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3
solution = Movingaverage(array, window)

From         To  FlightNumber  RecentDelays              Airline
0    London      Paris         10045      [23, 47]               KLM(!)
1    Madrid      Milan         10055            []    <Air France> (12)
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )
3  Budapest      Paris         10075          [13]       12. Air France
4  Brussels     London         10085      [67, 32]          "Swiss Air"

## 5. In the RecentDelays column, the values have been entered into the  DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value  should be NaN. 



## Expand the Series of lists into a DataFrame named delays, rename the columns  delay_1, delay_2, etc. and replace the unwanted RecentDelays column in df  with delays. 


In [7]:
delay_array = df.RecentDelays.tolist()
delay_array


[[23, 47], [], [24, 43, 87], [13], [67, 32]]

In [8]:
delays = pd.DataFrame(delay_array)
delays

0     1     2
0  23.0  47.0   NaN
1   NaN   NaN   NaN
2  24.0  43.0  87.0
3  13.0   NaN   NaN
4  67.0  32.0   NaN

In [9]:
df[['delay_1', 'delay_2', 'delay_3']] = delays

In [10]:
df.drop('RecentDelays', axis=1, inplace=True)

In [12]:
df = df[['From', 'To', 'FlightNumber', 'Airline', 'delay_1', 'delay_2', 'delay_3']]
df

From         To  FlightNumber              Airline  delay_1  delay_2  \
0    London      Paris         10045               KLM(!)     23.0     47.0   
1    Madrid      Milan         10055    <Air France> (12)      NaN      NaN   
2    London  Stockholm         10065  (British Airways. )     24.0     43.0   
3  Budapest      Paris         10075       12. Air France     13.0      NaN   
4  Brussels     London         10085          "Swiss Air"     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN